name: CD-CLIENTES-QA

on:
  workflow_dispatch:
  
env:
  SSH_PRIVATE_KEY: ${{ secrets.PEM_CLIENTES_QA }}
  REMOTE_USER: ec2-user
  REMOTE_HOST: ${{ secrets.IP_CLIENTES_QA }}
  APP_NAME: app.js
  DOCKERHUB_TOKEN: ${{ secrets.DH_TOKEN_CLIENTES }}
  DOCKERHUB_USERNAME: romicalani

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Iniciar sesion en Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}
        
    - name: Generar y Subir imagen Docker
      uses: docker/build-push-action@v4
      with:
        context: .
        file: /Dockerfile
        push: true
        tags: ${{ env.DOCKERHUB_USERNAME }}/my-node-app:latest
