name: CD-CLIENTES-QA

on:
  workflow_dispatch:
  
env:
  SSH_PRIVATE_KEY: ${{ secrets.PEM_CLIENTES_QA }}
  REMOTE_USER: ec2-user
  REMOTE_HOST: ${{ secrets.IP_CLIENTES_QA }}
  APP_NAME: app.js
  DOCKERHUB_TOKEN: ${{ secrets.DH_TOKEN_CLIENTES }}
  DOCKERHUB_USERNAME: romicalani

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: ver
      run: |
        ls -la
        cat Dockerfile
    - name: Iniciar sesion en Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}
    
