on:
  push:
    branches:
      - maicol_ventas

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_HOST: ${{ secrets.IP_ventas_DEV }}
      EC2_USERNAME: ${{ secrets.USERS_COBRANZAS }}
      EC2_SSH_KEY: ${{ secrets.PEM_VENTAS_DEV }}
      GH_TOKEN: ${{ secrets.TOKEN_COBRANZAS }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Check if directory exists
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_SSH_KEY }}
          script: |
            if [ -d "/opt/ms-ventas-dev-app" ]; then
              echo "Directory already exists."
            else
              echo "Directory does not exist. Creating directory..."
              sudo mkdir -p /opt/ms-ventas-dev-app
            fi

      - name: Install Git
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_SSH_KEY }}
          script: |
            sudo yum update -y && sudo yum install -y git

      - name: Clone repository
        uses: appleboy/ssh-action@master 
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_SSH_KEY }}
          script: |
            cd /opt
            sudo rm -rf /opt/ms-ventas-dev-app
            sudo git clone -b maicol_ventas https://${{ secrets.TOKEN_COBRANZAS }}@github.com/alkemyTech/UMSA-DevOps-T3 /opt/ms-ventas-dev-app

      - name: Install npm if not installed
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_SSH_KEY }}
          script: |
            if ! command -v npm &> /dev/null; then
              sudo yum install -y npm
            fi

      - name: Update environment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_SSH_KEY }}
          script: |
            sudo env PATH="$PATH" pm2 status

      - name: Install npm packages
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_SSH_KEY }}
          script: |
            cd /opt/ms-ventas-dev-app
            sudo npm install express pm2

      - name: Restart or Start app.js
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_SSH_KEY }}
          script: |
            cd /opt/ms-ventas-dev-app
            sudo ls -l
            sudo $(which pm2) status
            sudo $(which pm2) restart app.js || sudo $(which pm2) start -f app.js

      - name: Check service status
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_SSH_KEY }}
          script: |
            sudo $(which pm2) status

