name: CI Pagos DEV
env:
          SSH_PRIVATE_KEY: ${{ secrets.PEM_ORG_PAGOS_DEV }}
          REMOTE_USER: ec2-user
          REMOTE_HOST: ${{ secrets.IP_PAGOS_DEV }}
          APP_NAME: app.js
on:
  push:
    branches:
      - franco-pagos

jobs:
  ci-pagos-dev:
    name: CI en Pagos
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Instalar paquetes Node.js, NPM y Git
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ env.REMOTE_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            sudo yum install -y nodejs npm git
            
      - name: Crear directorio de trabajo en la máquina EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ env.REMOTE_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            sudo rm -rf /opt/ms-pagos-dev-app || true
            sudo mkdir -p /opt/ms-pagos-dev-app
            
      - name: Clonar repositorio de GitHub
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ env.REMOTE_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/ms-pagos-dev-app
            sudo git clone -b franco-pagos https://${{ secrets.TOKEN_PAGOS }}@github.com/alkemyTech/UMSA-DevOps-T3 .
            
      - name: Instalar paquetes NPM en la Máquina Virtual
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ env.REMOTE_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
                cd /opt/ms-pagos-dev-app
                # Verificar si express está instalado globalmente
                if ! npm list -g -depth 0 express > /dev/null; then
                  echo "Instalando express..."
                  sudo npm install express -g 
                else
                  echo "Express ya está instalado."
                fi
      
                # Verificar si pm2 está instalado globalmente
                if ! npm list -g -depth 0 pm2 > /dev/null; then
                  echo "Instalando pm2..."
                  sudo npm install pm2 -g 
                else
                  echo "PM2 ya está instalado."
                fi
            
      - name: Iniciar el servicio en Node con PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ env.REMOTE_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
                cd /opt/ms-pagos-dev-app
                if ! npm list > /dev/null; then
                  echo "Instalando paquetes npm..."
                  sudo npm install
                else
                  echo "Los paquetes npm ya están instalados."
                fi
      
                sudo pm2 start app.js -f
            
      - name: Chequear si la aplicación está corriendo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ env.REMOTE_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/ms-pagos-dev-app
            if curl http://localhost:3000 > /dev/null; then
              echo "App is running."
            else
              echo "App is not running."
              exit 1
            fi
