name: CI Pagos qa
env:
          SSH_PRIVATE_KEY: ${{ secrets.PEM_ORG_PAGOS_DEV }}
          REMOTE_USER: ec2-user
          REMOTE_HOST: ${{ secrets.IP_PAGOS_QA }}
          APP_NAME: app.js
on:
  push:
    branches:
      - franco-pagos-qa

jobs:
  ci-pagos-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Instalar Docker
      - name: Install Docker
        run: |
          sudo apt-get update -y
          sudo apt-get install -y docker

      # Construir la imagen Docker
      - name: Build Docker image
        run: |
          docker build -t pagosimagen .

      # Autenticación en DockerHub
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERPAGO_TOKEN }}" | docker login -u "${{ secrets.dockerUserpago }}" --password-stdin

      # Subir imagen a DockerHub
      - name: Push image to DockerHub
        run: docker push pagosimagen

      # Despliegue al entorno de QA (manual)
      - name: Desplegar al entorno de QA
        if: always()
        run: echo "Presiona un botón para desplegar en QA"
