on:
  push:
    branches:
    - maicol_cobranzas

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_HOST: ${{ secrets.IP_cobranzas_DEV }}
      EC2_USERNAME: ${{ secrets.USERS_COBRANZAS }}
      EC2_SSH_KEY: ${{ secrets.PEM_ORG_COBRANZAS_DEV }}
      GH_TOKEN: ${{ secrets.TOKEN_COBRANZAS }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Check if directory exists
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_SSH_KEY }}
          script: |
            if [ -d "/opt/ms-cobranzas-dev-app" ]; then
              echo "Directory already exists."
            else
              echo "Directory does not exist. Creating directory..."
              sudo mkdir -p /opt/ms-cobranzas-dev-app
            fi
     
      - name: Install Git
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_SSH_KEY }}
          script: |
            sudo yum update -y && sudo yum install -y git
      
      - name: Clone repository
        uses: appleboy/ssh-action@master 
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_SSH_KEY }}
          script: |
            cd /opt
            sudo rm -rf /opt/ms-cobranzas-dev-app
            sudo git clone -b maicol_cobranzas https://${{ secrets.TOKEN_COBRANZAS }}@github.com/alkemyTech/UMSA-DevOps-T3 /opt/ms-cobranzas-dev-app
      
      - name: Install npm if not installed
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_SSH_KEY }}
          script: |
            if ! command -v npm &> /dev/null; then
              sudo yum install -y npm
            fi

      - name: Install npm packages
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_SSH_KEY }}
          script: |
            cd /opt/ms-cobranzas-dev-app
            sudo npm install
    
      - name: Install npm packages and PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_SSH_KEY }}
          script: |
            cd /opt/ms-cobranzas-dev-app
            
            sudo npm install -g pm2
    
      - name: Start app.js with PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_SSH_KEY }}
          script: |
            app_dir="/opt/ms-cobranzas-dev-app"
            app_name="app.js"
            pm2=$(which pm2)

            # Verificar si la aplicación ya está instalada y en ejecución con PM2
            if sudo $pm2 list | grep -q "\<${app_name}\>"; then
              echo "La aplicación '${app_name}' ya está instalada. Reiniciando..."
                sudo $pm2 restart $app_name
            else
                echo "La aplicación '${app_name}' no está instalada. Instalando..."
                cd $app_dir
                sudo $pm2 start -f $app_name
            fi
 
      - name: Check service status
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_SSH_KEY }}
          script: |
            sudo $(which pm2) status
