name: CI Cobranzas DEV

on:
  push:
    branches:
      - maicol_cobranzas

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_HOST: ${{ secrets.IP_COBRANZAS_DEV }}
      EC2_USERNAME: ${{ secrets.USERS_COBRANZAS }}
      EC2_SSH_KEY: ${{ secrets.PEM_ORG_COBRANZAS_DEV }}
      GH_TOKEN: ${{ secrets.TOKEN_COBRANZAS }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    # Instalación de dependencias, creación de directorio y clonación de repositorio omitidos por brevedad

    - name: Install npm packages
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.EC2_HOST }}
        username: ${{ env.EC2_USERNAME }}
        key: ${{ env.EC2_SSH_KEY }}
        script: |
          cd /opt/ms-cobranzas-dev-app
          sudo npm install express pm2

    - name: Verify if app.js is already running
      uses: appleboy/ssh-action@master
      id: verify-pm2
      with:
        host: ${{ env.EC2_HOST }}
        username: ${{ env.EC2_USERNAME }}
        key: ${{ env.EC2_SSH_KEY }}
        script: |
          cd /opt/ms-cobranzas-dev-app
          sudo pm2 status app.js

    - name: Print PM2 status
      run: echo "${{ steps.verify-pm2.outputs.stdout }}"

    - name: Restart app.js if already running
      if: steps.verify-pm2.outputs.exit_code == 0
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.EC2_HOST }}
        username: ${{ env.EC2_USERNAME }}
        key: ${{ env.EC2_SSH_KEY }}
        script: |
          cd /opt/ms-cobranzas-dev-app
          sudo pm2 restart app.js

    - name: Start app.js if not already running
      if: steps.verify-pm2.outputs.exit_code != 0
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.EC2_HOST }}
        username: ${{ env.EC2_USERNAME }}
        key: ${{ env.EC2_SSH_KEY }}
        script: |
          cd /opt/ms-cobranzas-dev-app
          sudo pm2 start -f app.js

    - name: Check service status
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.EC2_HOST }}
        username: ${{ env.EC2_USERNAME }}
        key: ${{ env.EC2_SSH_KEY }}
        script: |
          sudo pm2 status
