name: Deploy Application

on:
  push:
    branches:
      - martin-prov-qa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Docker image
        run: |
          docker pull 471626/martin-prov-qa
          docker run -d -p 3000:3000 471626/martin-prov-qa:imagen-prov-qa
