name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Seleccione el entorno de destino'
        required: true
        default: 'QA'
        options:
          - 'QA'
          - 'Producción'

jobs:
  ci-pagos-qa:
    runs-on: ubuntu-latest

    steps:
      - name: Paso 1
        run: echo "Este es el paso 1"

      - name: Paso 2
        run: echo "Este es el paso 2"
