name: pagos-qa

on:
  workflow_dispatch:
    #inputs:
    #  environment:
    #    description: 'Deployment environment'
    #    required: true
    #    default: 'QA'
    #    options:
    #      - 'QA'
    #      - 'DEV'

jobs:
  check-branch:
    name: branch - ${{ github.ref }}
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
    
