name: pagos-qa

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true

jobs:
  check-branch:
    name: branch - ${{ github.ref }}
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
    
