name: Compras SSH

env:
  SSH_PRIVATE_KEY: ${{ secrets.PEM_FILE }}
  REMOTE_USER: ec2-user
  REMOTE_HOST: ${{ vars.AWS_DEV_HOST }}
  APP_NAME: app.js

on:
  push:
    branches:
      - gonzalo-compras  # Cambiar a la rama correspondiente si es diferente

jobs:
  ssh_job:
    name: SSH Job
    runs-on: ubuntu-latest  # Se puede cambiar a otra versión o SO según sea necesario

    steps:
    
      - name: Ejecutar comando SSH
        uses: appleboy/ssh-action@v1.0.3
       
            
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ env.REMOTE_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            sudo rm -rf /opt/compras || true