name: Delete Directory

on:
  push:
    branches:
      - martin-proveedorees

jobs:
  delete_directory:
    name: Delete Directory on Remote Server
    runs-on: ubuntu-latest

    env:
      SSH_PRIVATE_KEY: $ secrets.PEM_PROV_DEV
      REMOTE_USER: ec2-user
      REMOTE_HOST: $ secrets.AWS_DEV_HOST 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Delete directory on remote server
      uses: appleboy/ssh-action@master
      with:
        host: $ env.REMOTE_HOST 
        username: $ env.REMOTE_USER 
        key: $ secrets.PEM_PROV_DEV
        script: |
          sudo rm -rf /opt/montoto || true
